workspace = { members = ["src/funcoes"] }
[package]
name = "paraju"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

funcoes = {path ='src/funcoes'}